#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l vmem=14gb
#PBS -l walltime=0:30:00
#PBS -N app-combine-parcellation
#PBS -V

set -x
set -e

echo "combining parcellations"
singularity exec docker://brainlife/dipy:1.4.1 ./combine_parcellations.py

if [ ! -f parcellation/parc.nii.gz ]; then
	echo "something went wrong. check logs and derivatives"
	exit 1
else
	echo "complete"
	exit 0
fi
